// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKEdrjN9E6OB1hQX1BSIGLAaCDv1VOF_Q',
    appId: '1:326840974680:web:5d4250f34dfc553883f92d',
    messagingSenderId: '326840974680',
    projectId: 'madoi-70741',
    authDomain: 'madoi-70741.firebaseapp.com',
    storageBucket: 'madoi-70741.firebasestorage.app',
    measurementId: 'G-CDS11SRDYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuGscH-yiMre7oSWDKmrzM8lJDg3H4sGg',
    appId: '1:326840974680:android:dd3507e6f7c8c14f83f92d',
    messagingSenderId: '326840974680',
    projectId: 'madoi-70741',
    storageBucket: 'madoi-70741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAuzzfBEvtK_G8IILOYSdv3Yl0zeXrqEg',
    appId: '1:326840974680:ios:783b1c185c2c51cf83f92d',
    messagingSenderId: '326840974680',
    projectId: 'madoi-70741',
    storageBucket: 'madoi-70741.firebasestorage.app',
    iosClientId:
        '326840974680-01gn12q9f0alnb7hd92etqc687a7bi1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.madoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAuzzfBEvtK_G8IILOYSdv3Yl0zeXrqEg',
    appId: '1:326840974680:ios:783b1c185c2c51cf83f92d',
    messagingSenderId: '326840974680',
    projectId: 'madoi-70741',
    storageBucket: 'madoi-70741.firebasestorage.app',
    iosClientId:
        '326840974680-01gn12q9f0alnb7hd92etqc687a7bi1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.madoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKEdrjN9E6OB1hQX1BSIGLAaCDv1VOF_Q',
    appId: '1:326840974680:web:f9e7dae0c0bbc24d83f92d',
    messagingSenderId: '326840974680',
    projectId: 'madoi-70741',
    authDomain: 'madoi-70741.firebaseapp.com',
    storageBucket: 'madoi-70741.firebasestorage.app',
    measurementId: 'G-1HT9JR355V',
  );
}
